LASTFM_API_KEY=2c6d82257d67111ff3f71736b2a0469b
SPOTIFY_CLIENT_ID=d28df89507ca47bebaa9385ebb546e92
SPOTIFY_CLIENT_SECRET=f79edbcfd91f4958a9cdfb801afcbb9e
SPOTIFY_REDIRECT_URI=http://localhost:8501
SPOTIFY_ACCESS_TOKEN=BQDD67OG6n_-wb-2CkF7Ft13XWXXs3Hn4-YqrL42DChX2p9tQ_v01WWdHhtcnHgD6JmqOfn38Fflj81bsQxWcN-WrKPLuXb1ub66I0nNjVgJFsnpvmbFDKSvDUtbaPxwV4C9COGmJfE